# Set the Cursor
xsetroot -cursor_name left_ptr

# Import Xresources
xrdb ~/.Xresources

# Start trayer
trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 5 --transparent true --alpha 0 --tint 0x000000 -height 16 &

# Start VboxClient
sudo VBoxClient-all &
# Start Xmonad
exec xmonad
